// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacationRental.Infra;

namespace VacationRental.Infra.Migrations
{
    [DbContext(typeof(VacationRentalContext))]
    [Migration("20230127002305_First_Migration")]
    partial class First_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VacationRental.Domain.Bookings.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CalendarDateId");

                    b.Property<int>("Nights");

                    b.Property<int>("RentalId");

                    b.Property<int>("Unity");

                    b.HasKey("Id");

                    b.HasIndex("CalendarDateId");

                    b.HasIndex("RentalId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("VacationRental.Domain.Calendars.CalendarDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("CalendarDates");
                });

            modelBuilder.Entity("VacationRental.Domain.PreparationTimes.PreparationTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfPreparation");

                    b.Property<int?>("RentalId");

                    b.HasKey("Id");

                    b.HasIndex("RentalId");

                    b.ToTable("PreparationTimes");
                });

            modelBuilder.Entity("VacationRental.Domain.Rentals.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Units");

                    b.HasKey("Id");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("VacationRental.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("VacationRental.Domain.Calendars.CalendarDate", "CalendarDate")
                        .WithMany("Bookings")
                        .HasForeignKey("CalendarDateId");

                    b.HasOne("VacationRental.Domain.Rentals.Rental", "Rental")
                        .WithMany("Bookings")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VacationRental.Domain.PreparationTimes.PreparationTime", b =>
                {
                    b.HasOne("VacationRental.Domain.Rentals.Rental", "Rental")
                        .WithMany("PreparationTimes")
                        .HasForeignKey("RentalId");
                });
#pragma warning restore 612, 618
        }
    }
}
