// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VR.DataAccess;

namespace VR.DataAccess.Migrations
{
    [DbContext(typeof(VRContext))]
    [Migration("20220830142631_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("VR.Domain.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Nights")
                        .HasColumnType("int");

                    b.Property<int>("RentalId")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblBooking_BookingId");

                    b.HasIndex("RentalId");

                    b.ToTable("tblBooking");
                });

            modelBuilder.Entity("VR.Domain.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("PreparationTimeInDays")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<int>("Units")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblRental_RentalId");

                    b.ToTable("tblRental");
                });

            modelBuilder.Entity("VR.Domain.Models.Booking", b =>
                {
                    b.HasOne("VR.Domain.Models.Rental", "Rental")
                        .WithMany("Bookings")
                        .HasForeignKey("RentalId")
                        .HasConstraintName("FK_tblAthlete_tblTeam")
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("VR.Domain.Models.Rental", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
